const PHOTOS = {
  SHOW_NEXT: 'PHOTOS/SHOW_NEXT',
  SHOW_PREVIOUS: 'PHOTOS/SHOW_PREVIOUS',
  FETCH_ALBUM_REQUEST: 'PHOTOS/FETCH_ALBUM_REQUEST',
  FETCH_ALBUM_SUCCESS: 'PHOTOS/FETCH_ALBUM_SUCCESS',
  FETCH_ALBUM_FAILURE: 'PHOTOS/FETCH_ALBUM_FAILURE',
};

const actionTypes = {
  PHOTOS,
};

export default actionTypes;
